

@baseurl = http://localhost:3000


# Bicicletas

Get {{baseurl}}/bicicleta
###


PUT {{baseurl}}/bicicleta/3/
Content-Type: application/json

{   
    "ano": "2025",
    "modelo": "monarc",
    "marca": "vermelho"
}


###
POST {{baseurl}}/bicicleta/
Content-Type: application/json

{   
    "ano": "22222",
    "modelo": "eeee",
    "marca": "ccc"
}



###

DELETE {{baseurl}}/bicicletas/1/
Content-Type: application/json

{   
    "ano": "2025",
    "modelo": "monarc",
    "marca": "vermelho"
} 

###
POST http://localhost:3000/bicicleta/integrarNaRede/
Content-Type: application/json
{
   "idBicicleta": "3",
    "idTranca": "1",
    "idFuncionario": "2"
}


### TRANCAS

Get {{baseurl}}/trancas/
###


PUT {{baseurl}}/trancas/1/
Content-Type: application/json

{   
    "anoDeFabricacao": "2000"
}


###
POST {{baseurl}}/trancas/
Content-Type: application/json

{   
    "anoDeFabricacao": "2222",
    "modelo": "ccccc"
}

POST {{baseurl}}/trancas/
Content-Type: application/json
{
   "idBicicleta": "3",
    "idTranca": "1",
    "idFuncionario": "2"
}

###

POST {{baseurl}}/incluir-no-totem/
Content-Type: application/json
 {
     "trancaId": "1",
     "totemId": "1"
     }

###

DELETE {{baseurl}}/trancas/1/



### TOTEM

Get {{baseurl}}/totem/
###


PUT {{baseurl}}/totem/1/
Content-Type: application/json

{   
    "anoDeFabricacao": "2000"
}


###
POST {{baseurl}}/totem/
Content-Type: application/json

{   
    "localizacao": "amage2",
    "descricao": "aaaperto da Upa2"
}



###

DELETE {{baseurl}}/totem/5/
