@baseurl = http://localhost:3000

### BICICLETAS

# Obter todas as bicicletas
GET {{baseurl}}/bicicleta/
###

# Atualizar dados de uma bicicleta
PUT {{baseurl}}/bicicleta/1/
Content-Type: application/json

{   
    "ano": "2006",
    "modelo": "Tarmac",
    "marca": "Specialized"
}
###

# Criar uma nova bicicleta
POST {{baseurl}}/bicicleta
Content-Type: application/json

{   
    "ano": "2000",
    "modelo": "Delabeneta",
    "marca": "marca_a"
}
###

# Excluir uma bicicleta
DELETE {{baseurl}}/bicicleta/2/
###

# Integrar bicicleta na rede
POST {{baseurl}}/bicicleta/integrarNaRede/
Content-Type: application/json

{
   "idBicicleta": 1,
   "idTranca": 1,
   "idFuncionario": 0
}
###

### mudar status

POST {{baseurl}}/bicicleta/2/status/APOSENTAR/



###
# retirar da Rede 
POST {{baseurl}}/bicicleta/retirarDaRede/
Content-Type: application/json

{
   "idBicicleta": 1,
   "idTranca": 1,
   "idFuncionario": 0,
   "opcao": "REPARO"
}

### TRANCAS

# Obter todas as trancas
GET {{baseurl}}/tranca/
###

# Atualizar dados de uma tranca
PUT {{baseurl}}/tranca/1/
Content-Type: application/json

{   
    "anoDeFabricacao": "2000"
}
###

# Integrar tranca na rede
POST {{baseurl}}/tranca/integrarNaRede
Content-Type: application/json

{
    "idTranca": 1,
    "idFuncionario": 0,
    "idTotem": 1
}

###

GET {{baseurl}}/totem/1/trancas
###

GET {{baseurl}}/tranca
###
POST {{baseurl}}/tranca/destrancar
Content-Type: application/json

{
    "idTranca": 1,
    "idBicicleta": 1
}

###

# Criar uma nova tranca
POST {{baseurl}}/tranca/
Content-Type: application/json

{   
    "anoDeFabricacao": "2000",
    "modelo": "Delabeneta"
}
####

# Excluir uma tranca
DELETE {{baseurl}}/tranca/1/
###

### TOTEM

# Obter todos os totens
GET {{baseurl}}/totem/1/trancas
###

# Atualizar dados de um totem
PUT {{baseurl}}/totem/1/
Content-Type: application/json

{   
    "anoDeFabricacao": "2000"
}
###

# Criar um novo totem
POST {{baseurl}}/totem/
Content-Type: application/json

{   
    "localizacao": "Botafogo",
    "descricao": "Praia Shopping"
}
###

# Excluir um totem
DELETE {{baseurl}}/totem/1
###
