services:
  nestjs-app:
    build: .
    container_name: sqlite_container
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data  # Persistir o arquivo SQLite fora do contêiner
    environment:
      - DATABASE_NAME=/app/data/data.db  # Definindo o caminho do banco de dados dentro do contêiner
